package com.ebookreader.simplebook.domain.model

data class AppStrings(
    val settings: String,
    val fontSize: String,
    val lineHeight: String,
    val themeSetting: String,
    val defaultWhite: String,
    val sepia: String,
    val cherryPink: String,
    val mintGreen: String,
    val sapphireBlue: String,
    val nightSakura: String,
    val darkGreen: String,
    val deepSea: String,
    val nightMode: String,
    val lightTheme: String,
    val about: String,
    val language: String,
    val chinese: String,
    val english: String,
    val nextChapter: String,
    val allChaptersRead: String,
    val endOfChapter: String,
    val continueQuestion: String,
    val continueBtn: String,
    val stayBtn: String,
    val addNote: String,
    val noteContent: String,
    val save: String,
    val cancel: String,
    val noContent: String,
    val emptyShelfTitle: String,
    val emptyShelfHint: String,
    val emptyCollectionTitle: String,
    val unknownAuthor: String,
    val navBooks: String,
    val navFavorites: String,
    val navSettings: String,
    val importBook: String,
    val deleteBook: String,
    val delete: String,
    val deleteMessage: (bookTitle: String) -> String,
    val chapterOf: (current: Int, total: Int) -> String,
    // Sync
    val syncTitle: String,
    val syncSignIn: String,
    val syncSignOut: String,
    val syncNow: String,
    val syncSignedIn: String,
    val syncDescription: String,
    val syncSettingsTitle: String,
    val syncSettingsDescription: String,
    val autoSyncLabel: String,
    val syncConflicts: String,
    val syncNoConflicts: String,
    val syncKeepLocal: String,
    val syncUseRemote: String,
    val syncBack: String,
    val cleanDriveTitle: String,
    val cleanDriveDescription: String,
    val cleanDriveButton: String,
    val cleanDriveNoDeleted: String,
    val cleanDriveScanning: String,
    val cleanDriveCleaning: String,
    val cleanDriveResult: (count: Int, size: String) -> String,
    val cleanDriveFound: (count: Int, size: String) -> String,
    val cleanDriveConfirm: String,
    val cleanDriveDone: String,
    val cleanDriveConfirmMessage: (count: Int) -> String,
    // Drive Import
    val driveImportTitle: String,
    val driveImportDescription: String,
    val driveImportButton: String,
    val driveImporting: String,
    val driveImportResult: (count: Int) -> String,
    val driveImportEmpty: String,
    val layoutLargeGrid: String,
    val layoutSmallGrid: String,
    val layoutList: String,
    // Folder
    val createFolder: String,
    val folderName: String,
    val moveToFolder: String,
    val moveBackToShelf: String,
    val noFolders: String,
    val bookCount: (count: Int) -> String,
    // Sort
    val sortByLastRead: String,
    val sortByName: String,
    // Speed Dial
    val importBooks: String,
    val newFolder: String,
    val sort: String,
    // Drag-and-drop import (desktop)
    val dropHereToImport: String
)

fun getStrings(language: String): AppStrings = when (language) {
    "en" -> AppStrings(
        settings = "Settings",
        fontSize = "Font Size",
        lineHeight = "Line Height",
        themeSetting = "Theme",
        defaultWhite = "White",
        sepia = "Sepia",
        cherryPink = "Cherry Pink",
        mintGreen = "Mint Green",
        sapphireBlue = "Sapphire Blue",
        nightSakura = "Night Sakura",
        darkGreen = "Dark Green",
        deepSea = "Deep Sea",
        nightMode = "Night Mode",
        lightTheme = "Light",
        about = "About",
        language = "Language",
        chinese = "中文",
        english = "English",
        nextChapter = "Next Chapter →",
        allChaptersRead = "All chapters read",
        endOfChapter = "End of Chapter",
        continueQuestion = "Continue to the next chapter?",
        continueBtn = "Continue",
        stayBtn = "Stay",
        addNote = "Add Note",
        noteContent = "Note content",
        save = "Save",
        cancel = "Cancel",
        noContent = "No books yet. Tap + to import.",
        emptyShelfTitle = "No Books Yet",
        emptyShelfHint = "Tap + to import your first book",
        emptyCollectionTitle = "No Favorites Yet",
        unknownAuthor = "Unknown",
        navBooks = "Books",
        navFavorites = "Favorites",
        navSettings = "Settings",
        importBook = "Import books",
        deleteBook = "Delete Book",
        delete = "Delete",
        deleteMessage = { title -> "Are you sure you want to delete \"$title\"?" },
        chapterOf = { current, total -> "Chapter $current of $total" },
        // Sync
        syncTitle = "Google Drive Sync",
        syncSignIn = "Sign in with Google Drive",
        syncSignOut = "Sign Out",
        syncNow = "Sync Now",
        syncSignedIn = "Signed in: %s",
        syncDescription = "Sync your books and reading progress across devices",
        syncSettingsTitle = "Sync Settings",
        syncSettingsDescription = "When off, sync only when you tap Sync now",
        autoSyncLabel = "Auto Sync",
        syncConflicts = "Resolve Conflicts",
        syncNoConflicts = "No conflicts",
        syncKeepLocal = "Keep Local",
        syncUseRemote = "Use Remote",
        syncBack = "Back",
        cleanDriveTitle = "Drive Cleanup",
        cleanDriveDescription = "Permanently remove deleted books from Google Drive to free up storage.",
        cleanDriveButton = "Clean Deleted Books from Drive",
        cleanDriveScanning = "Scanning Drive...",
        cleanDriveNoDeleted = "No deleted books to clean",
        cleanDriveCleaning = "Cleaning...",
        cleanDriveResult = { count, size -> "Cleaned $count books, freed ~$size" },
        cleanDriveFound = { count, size -> "Found $count deleted books (~$size) on Drive" },
        cleanDriveConfirm = "Confirm Clean",
        cleanDriveDone = "OK",
        cleanDriveConfirmMessage = { count -> "Permanently delete $count books from Google Drive. This cannot be undone." },
        // Drive Import
        driveImportTitle = "Import from Drive",
        driveImportDescription = "Put epub/txt files in Google Drive → SimpleBook → Import folder, then tap the button below.",
        driveImportButton = "Import from Drive",
        driveImporting = "Importing from Drive...",
        driveImportResult = { count -> "Successfully imported $count books" },
        driveImportEmpty = "No new books found in Import folder",
        layoutLargeGrid = "Large Grid",
        layoutSmallGrid = "Small Grid",
        layoutList = "List View",
        createFolder = "New Folder",
        folderName = "Folder name",
        moveToFolder = "Move to Folder",
        moveBackToShelf = "Move to Shelf",
        noFolders = "No folders yet. Create one first.",
        bookCount = { count -> "$count books" },
        sortByLastRead = "By Last Read",
        sortByName = "By Name",
        importBooks = "Import Books",
        newFolder = "New Folder",
        sort = "Sort",
        dropHereToImport = "Drop books here to import"
    )
    else -> AppStrings(
        settings = "设置",
        fontSize = "字体大小",
        lineHeight = "行高",
        themeSetting = "主题设置",
        defaultWhite = "默认白",
        sepia = "护眼黄",
        cherryPink = "樱花粉",
        mintGreen = "薄荷绿",
        sapphireBlue = "宝石蓝",
        nightSakura = "夜樱",
        darkGreen = "暗草绿",
        deepSea = "深海蓝",
        nightMode = "夜间模式",
        lightTheme = "明亮主题",
        about = "关于",
        language = "语言",
        chinese = "中文",
        english = "English",
        nextChapter = "下一章 →",
        allChaptersRead = "已读完全部章节",
        endOfChapter = "章节结束",
        continueQuestion = "是否继续阅读下一章？",
        continueBtn = "继续",
        stayBtn = "留下",
        addNote = "添加笔记",
        noteContent = "笔记内容",
        save = "保存",
        cancel = "取消",
        noContent = "暂无书籍，点击 + 导入",
        emptyShelfTitle = "暂无书籍",
        emptyShelfHint = "点击 + 导入",
        emptyCollectionTitle = "暂无收藏",
        unknownAuthor = "未知",
        navBooks = "书架",
        navFavorites = "收藏",
        navSettings = "设置",
        importBook = "导入书籍",
        deleteBook = "删除书籍",
        delete = "删除",
        deleteMessage = { title -> "确认删除「$title」吗？" },
        chapterOf = { current, total -> "第 $current 章 / 共 $total 章" },
        // Sync
        syncTitle = "Google Drive 同步",
        syncSignIn = "登录 Google Drive",
        syncSignOut = "退出登录",
        syncNow = "立即同步",
        syncSignedIn = "已登录：%s",
        syncDescription = "在设备之间同步您的书籍和阅读进度",
        syncSettingsTitle = "同步设置",
        syncSettingsDescription = "关闭后仅在点击「立即同步」时同步",
        autoSyncLabel = "自动同步",
        syncConflicts = "解决冲突",
        syncNoConflicts = "没有冲突",
        syncKeepLocal = "全部保留本地",
        syncUseRemote = "全部使用远端",
        syncBack = "返回",
        cleanDriveTitle = "网盘清理",
        cleanDriveDescription = "在 Google Drive 中清除已删除的书籍。",
        cleanDriveButton = "清除网盘已删除书籍",
        cleanDriveScanning = "正在扫描网盘...",
        cleanDriveNoDeleted = "没有需要清除的书籍",
        cleanDriveCleaning = "正在清除...",
        cleanDriveResult = { count, size -> "已清理 $count 本书籍，释放约 $size 空间" },
        cleanDriveFound = { count, size -> "在网盘中发现 $count 本已删除书籍（约 $size）" },
        cleanDriveConfirm = "确认清除",
        cleanDriveDone = "确定",
        cleanDriveConfirmMessage = { count -> "将从 Google Drive 中永久删除 $count 本书籍及其数据，此操作不可撤销。" },
        // Drive Import
        driveImportTitle = "从 Drive 导入",
        driveImportDescription = "将 epub/txt 文件放入 Google Drive → SimpleBook → Import 文件夹，然后点击下方按钮导入。",
        driveImportButton = "从 Drive 导入",
        driveImporting = "正在从 Drive 导入...",
        driveImportResult = { count -> "成功导入 $count 本书籍" },
        driveImportEmpty = "Import 文件夹中没有新书",
        layoutLargeGrid = "大网格视图",
        layoutSmallGrid = "小网格视图",
        layoutList = "列表视图",
        createFolder = "新建文件夹",
        folderName = "文件夹名称",
        moveToFolder = "移入文件夹",
        moveBackToShelf = "移回主书架",
        noFolders = "暂无文件夹，请先创建",
        bookCount = { count -> "共 $count 本" },
        sortByLastRead = "按最后阅读时间",
        sortByName = "按名称",
        importBooks = "导入书籍",
        newFolder = "新建文件夹",
        sort = "排序",
        dropHereToImport = "松开以导入书籍"
    )
}
