package com.ebookreader.simplebook.domain.model

data class AppStrings(
    val settings: String,
    val fontSize: String,
    val lineHeight: String,
    val background: String,
    val white: String,
    val sepia: String,
    val dark: String,
    val black: String,
    val about: String,
    val language: String,
    val chinese: String,
    val english: String,
    val nextChapter: String,
    val allChaptersRead: String,
    val endOfChapter: String,
    val continueQuestion: String,
    val continueBtn: String,
    val stayBtn: String,
    val addNote: String,
    val noteContent: String,
    val save: String,
    val cancel: String,
    val noContent: String,
    val unknownAuthor: String,
    val navBooks: String,
    val navFavorites: String,
    val navSettings: String,
    val importBook: String,
    val deleteBook: String,
    val delete: String,
    val deleteMessage: (bookTitle: String) -> String,
    val chapterOf: (current: Int, total: Int) -> String,
    // Sync
    val syncTitle: String,
    val syncSignIn: String,
    val syncSignOut: String,
    val syncNow: String,
    val syncSignedIn: String,
    val syncDescription: String,
    val syncConflicts: String,
    val syncNoConflicts: String,
    val syncKeepLocal: String,
    val syncUseRemote: String,
    val syncBack: String,
)

fun getStrings(language: String): AppStrings = when (language) {
    "en" -> AppStrings(
        settings = "Settings",
        fontSize = "Font Size",
        lineHeight = "Line Height",
        background = "Background",
        white = "White",
        sepia = "Sepia",
        dark = "Dark",
        black = "Black",
        about = "About",
        language = "Language",
        chinese = "中文",
        english = "English",
        nextChapter = "Next Chapter →",
        allChaptersRead = "All chapters read",
        endOfChapter = "End of Chapter",
        continueQuestion = "Continue to the next chapter?",
        continueBtn = "Continue",
        stayBtn = "Stay",
        addNote = "Add Note",
        noteContent = "Note content",
        save = "Save",
        cancel = "Cancel",
        noContent = "No books yet. Tap + to import.",
        unknownAuthor = "Unknown",
        navBooks = "Books",
        navFavorites = "Favorites",
        navSettings = "Settings",
        importBook = "Import books",
        deleteBook = "Delete Book",
        delete = "Delete",
        deleteMessage = { title -> "Are you sure you want to delete \"$title\"?" },
        chapterOf = { current, total -> "Chapter $current of $total" },
        // Sync
        syncTitle = "Google Drive Sync",
        syncSignIn = "Sign in with Google Drive",
        syncSignOut = "Sign Out",
        syncNow = "Sync Now",
        syncSignedIn = "Signed in: %s",
        syncDescription = "Sync your books and reading progress across devices",
        syncConflicts = "Resolve Conflicts",
        syncNoConflicts = "No conflicts",
        syncKeepLocal = "Keep Local",
        syncUseRemote = "Use Remote",
        syncBack = "Back",
    )
    else -> AppStrings(
        settings = "设置",
        fontSize = "字体大小",
        lineHeight = "行高",
        background = "背景色",
        white = "白色",
        sepia = "护眼",
        dark = "深色",
        black = "黑色",
        about = "关于",
        language = "语言",
        chinese = "中文",
        english = "English",
        nextChapter = "下一章 →",
        allChaptersRead = "已读完全部章节",
        endOfChapter = "章节结束",
        continueQuestion = "是否继续阅读下一章？",
        continueBtn = "继续",
        stayBtn = "留下",
        addNote = "添加笔记",
        noteContent = "笔记内容",
        save = "保存",
        cancel = "取消",
        noContent = "暂无书籍，点击 + 导入",
        unknownAuthor = "未知",
        navBooks = "书架",
        navFavorites = "收藏",
        navSettings = "设置",
        importBook = "导入书籍",
        deleteBook = "删除书籍",
        delete = "删除",
        deleteMessage = { title -> "确认删除「$title」吗？" },
        chapterOf = { current, total -> "第 $current 章 / 共 $total 章" },
        // Sync
        syncTitle = "Google Drive 同步",
        syncSignIn = "登录 Google Drive",
        syncSignOut = "退出登录",
        syncNow = "立即同步",
        syncSignedIn = "已登录：%s",
        syncDescription = "在设备之间同步您的书籍和阅读进度",
        syncConflicts = "解决冲突",
        syncNoConflicts = "没有冲突",
        syncKeepLocal = "全部保留本地",
        syncUseRemote = "全部使用远端",
        syncBack = "返回",
    )
}
